name: front_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  #로그인 관련
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0

  # UI 및 애니메이션
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8

  # 카메라 및 이미지
  camera: ^0.10.0
  image_picker: ^1.2.0

  # AI 모델
  tflite_flutter: ^0.10.0

  # 구글맵 관련 (추가)
  google_maps_flutter: ^2.5.0

  # 위치 정보 (추가)
  geolocator: ^10.1.0

  # HTTP 통신 (추가)
  http: ^1.1.0
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/